# Generated by Django 5.1 on 2024-09-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='national_id',
        ),
    ]
