# Generated by Django 5.1 on 2024-09-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_branch_email_alter_branch_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='branc',
            new_name='branch',
        ),
    ]
