# Generated by Django 5.1 on 2024-09-03 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_branc_department_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentsBranche', to='company.branch'),
        ),
    ]
